# coding:utf-8
from PySide6.QtDesigner import QPyDesignerCustomWidgetCollection
from basic_input_plugin import *
from container_plugin import *
from date_time_plugin import *
from navigation_plugin import *
from status_info_plugin import *
from text_plugin import *
from .view_plugin import *


# basic input plugins
QPyDesignerCustomWidgetCollection.addCustomWidget(CheckBoxPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(ComboBoxPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(FilledComboBoxPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SurfaceFloatingActionButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SecondaryFloatingActionButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(PrimaryFloatingActionButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TertiaryFloatingActionButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(OutlinedPushButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(FilledPushButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(ElevatedPushButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TonalPushButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(FilledToolButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(FilledToggleToolButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(OutlinedToolButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(OutlinedToggleToolButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TransparentToolButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TransparentToggleToolButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(RadioButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SliderPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SwitchButtonPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(IconWidgetPlugin())

# container plugins
QPyDesignerCustomWidgetCollection.addCustomWidget(ScrollAreaPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SmoothScrollAreaPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SingleDirectionScrollAreaPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(OpacityAniStackedWidgetPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(PopUpAniStackedWidgetPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(CardWidget())
QPyDesignerCustomWidgetCollection.addCustomWidget(OutlinedCardWidget())
QPyDesignerCustomWidgetCollection.addCustomWidget(ElevatedCardWidget())

# date time plugins
QPyDesignerCustomWidgetCollection.addCustomWidget(CalendarPickerPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TimePickerPlugin())

# navigation plugins
QPyDesignerCustomWidgetCollection.addCustomWidget(NavigationRailPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(NavigationBarPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TabWidgetPlugin())

# status info plugins
QPyDesignerCustomWidgetCollection.addCustomWidget(InfoBadgePlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(ProgressBarPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(ProgressRingPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(DotInfoBadgePlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(IconInfoBadgePlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(IndeterminateProgressBarPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(IndeterminateProgressRingPlugin())

# text plugins
QPyDesignerCustomWidgetCollection.addCustomWidget(LineEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(FilledLineEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SearchLineEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(FilledSearchLineEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(DateEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(DateTimeEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(DoubleSpinBoxPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(SpinBoxPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TimeEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TextEditPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(FilledTextEditPlugin())

# view plugins
QPyDesignerCustomWidgetCollection.addCustomWidget(ListViewPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(ListWidgetPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TableViewPlugin())
QPyDesignerCustomWidgetCollection.addCustomWidget(TableWidgetPlugin())
